import React, { useState, useEffect, useMemo, useRef } from 'react';
import { Question, Topic, QuizResult, Flashcard, TopicId } from '../types';
import {
  Award,
  Clock,
  RotateCcw,
  CheckCircle,
  XCircle,
  Bookmark,
  ChevronLeft,
  ChevronRight,
  Sparkles,
  HelpCircle,
  Play,
} from 'lucide-react';
import confetti from 'canvas-confetti';
import { generateQuestionsFromFlashcards } from '../data/quizQuestions';

interface QuizViewProps {
  questions: Question[];
  flashcards: Flashcard[];
  topics: Topic[];
  selectedTopic: TopicId | string;
  bookmarkedIds: number[];
  onToggleBookmark: (questionId: number) => void;
  onSaveQuizResult: (result: QuizResult) => void;
}

export const QuizView: React.FC<QuizViewProps> = ({
  questions,
  flashcards,
  topics,
  selectedTopic,
  bookmarkedIds,
  onToggleBookmark,
  onSaveQuizResult,
}) => {
  const [quizMode, setQuizMode] = useState<'selection' | 'active' | 'summary'>('selection');
  const [selectedDurationMinutes, setSelectedDurationMinutes] = useState<number>(5);
  const [selectedQuestionCount, setSelectedQuestionCount] = useState<number>(10);
  const [activeQuestions, setActiveQuestions] = useState<Question[]>([]);
  const [currentIdx, setCurrentIdx] = useState<number>(0);
  const [selectedAnswers, setSelectedAnswers] = useState<{ [qId: number]: number }>({});
  const [timeLeftSeconds, setTimeLeftSeconds] = useState<number>(300);
  const [filterWrongOnly, setFilterWrongOnly] = useState<boolean>(false);
  const timerRef = useRef<any>(null);

  // Generate complete pool combining static questions and auto-generated questions from current flashcards
  const questionPool = useMemo(() => {
    const autoGenerated = generateQuestionsFromFlashcards(flashcards);
    const combined = [...questions, ...autoGenerated];

    if (selectedTopic === 'all') {
      return combined;
    }
    return combined.filter((q) => q.topic === selectedTopic);
  }, [questions, flashcards, selectedTopic]);

  // Start Quiz
  const handleStartQuiz = () => {
    const shuffled = [...questionPool].sort(() => Math.random() - 0.5);
    const chosen = shuffled.slice(0, Math.min(selectedQuestionCount, shuffled.length));

    setActiveQuestions(chosen);
    setCurrentIdx(0);
    setSelectedAnswers({});
    setTimeLeftSeconds(selectedDurationMinutes * 60);
    setQuizMode('active');
    setFilterWrongOnly(false);
  };

  // Timer Tick
  useEffect(() => {
    if (quizMode === 'active') {
      timerRef.current = setInterval(() => {
        setTimeLeftSeconds((prev) => {
          if (prev <= 1) {
            clearInterval(timerRef.current);
            handleFinishQuiz();
            return 0;
          }
          return prev - 1;
        });
      }, 1000);
    } else {
      if (timerRef.current) clearInterval(timerRef.current);
    }

    return () => {
      if (timerRef.current) clearInterval(timerRef.current);
    };
  }, [quizMode]);

  // Answer selection
  const handleSelectAnswer = (questionId: number, optionIdx: number) => {
    if (selectedAnswers[questionId] !== undefined) return; // Answered already
    setSelectedAnswers((prev) => ({
      ...prev,
      [questionId]: optionIdx,
    }));
  };

  // Finish Quiz
  const handleFinishQuiz = () => {
    if (timerRef.current) clearInterval(timerRef.current);

    let correct = 0;
    activeQuestions.forEach((q) => {
      if (selectedAnswers[q.id] === q.correctIndex) {
        correct++;
      }
    });

    const result: QuizResult = {
      id: `quiz_${Date.now()}`,
      date: new Date().toISOString(),
      topic: selectedTopic,
      score: correct,
      total: activeQuestions.length,
      timeSpentSeconds: selectedDurationMinutes * 60 - timeLeftSeconds,
      answers: selectedAnswers,
    };

    onSaveQuizResult(result);
    setQuizMode('summary');

    // Confetti celebration if score >= 70%
    const percent = Math.round((correct / (activeQuestions.length || 1)) * 100);
    if (percent >= 70) {
      try {
        confetti({
          particleCount: 80,
          spread: 70,
          origin: { y: 0.6 },
        });
      } catch (e) {
        // Confetti fallback
      }
    }
  };

  const formatTime = (secs: number) => {
    const m = Math.floor(secs / 60);
    const s = secs % 60;
    return `${m.toString().padStart(2, '0')}:${s.toString().padStart(2, '0')}`;
  };

  const currentTopicObj = topics.find((t) => t.id === selectedTopic);

  // ═══════════════════════════════════════════════════════════════
  // 1. SELECTION SCREEN (Choose time & number of questions)
  // ═══════════════════════════════════════════════════════════════
  if (quizMode === 'selection') {
    return (
      <div className="max-w-4xl mx-auto px-4 py-8 space-y-8">
        
        {/* Banner */}
        <div className="bg-gradient-to-r from-rose-600 via-pink-600 to-indigo-600 rounded-3xl p-6 sm:p-8 text-white shadow-lg relative overflow-hidden">
          <div className="relative z-10 space-y-2 max-w-xl">
            <div className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full bg-white/20 backdrop-blur-md text-[11px] font-black tracking-wider uppercase">
              <HelpCircle className="w-3.5 h-3.5" /> Luyện Thi Trắc Nghiệm Phản Xạ
            </div>
            <h2 className="text-2xl sm:text-3xl font-black tracking-tight">
              Kiểm Tra & Củng Cố Trí Nhớ Từ Vựng
            </h2>
            <p className="text-xs sm:text-sm text-rose-50 leading-relaxed font-medium">
              Bài thi trắc nghiệm 4 đáp án tự động tổng hợp từ kho từ vựng và các thẻ flashcard bạn đã tạo.
            </p>
          </div>
        </div>

        {/* Configuration Box */}
        <div className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-3xl p-6 sm:p-8 space-y-6 shadow-xs">
          
          <div className="space-y-1">
            <h3 className="text-base font-extrabold text-slate-900 dark:text-white">
              Cấu Hình Bài Thi
            </h3>
            <p className="text-xs text-slate-500 dark:text-slate-400">
              Đang chọn chủ đề: <strong className="text-indigo-600 dark:text-indigo-400">{currentTopicObj?.title}</strong> ({questionPool.length} câu khả dụng)
            </p>
          </div>

          {/* Number of Questions */}
          <div className="space-y-2">
            <label className="text-xs font-bold text-slate-700 dark:text-slate-300">
              Số lượng câu hỏi:
            </label>
            <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
              {[5, 10, 15, 20].map((count) => (
                <button
                  key={count}
                  onClick={() => setSelectedQuestionCount(count)}
                  className={`p-3.5 rounded-2xl border text-xs font-bold transition cursor-pointer ${
                    selectedQuestionCount === count
                      ? 'bg-rose-50 dark:bg-rose-950/60 border-rose-500 text-rose-700 dark:text-rose-300 ring-2 ring-rose-500/20'
                      : 'bg-white dark:bg-slate-800 border-slate-200 dark:border-slate-700 text-slate-700 dark:text-slate-200 hover:bg-slate-50'
                  }`}
                >
                  {count} Câu Hỏi
                </button>
              ))}
            </div>
          </div>

          {/* Duration in Minutes */}
          <div className="space-y-2">
            <label className="text-xs font-bold text-slate-700 dark:text-slate-300">
              Thời gian làm bài:
            </label>
            <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
              {[3, 5, 10, 15].map((mins) => (
                <button
                  key={mins}
                  onClick={() => setSelectedDurationMinutes(mins)}
                  className={`p-3.5 rounded-2xl border text-xs font-bold transition cursor-pointer ${
                    selectedDurationMinutes === mins
                      ? 'bg-rose-50 dark:bg-rose-950/60 border-rose-500 text-rose-700 dark:text-rose-300 ring-2 ring-rose-500/20'
                      : 'bg-white dark:bg-slate-800 border-slate-200 dark:border-slate-700 text-slate-700 dark:text-slate-200 hover:bg-slate-50'
                  }`}
                >
                  {mins} Phút
                </button>
              ))}
            </div>
          </div>

          {/* Start Button */}
          <div className="pt-4">
            <button
              onClick={handleStartQuiz}
              disabled={questionPool.length === 0}
              className="w-full py-4 bg-gradient-to-r from-rose-600 via-pink-600 to-indigo-600 hover:from-rose-700 hover:to-indigo-700 text-white rounded-2xl text-sm font-extrabold transition shadow-lg shadow-rose-600/25 flex items-center justify-center gap-2 cursor-pointer disabled:opacity-40"
            >
              <Play className="w-5 h-5 fill-current" /> Bắt Đầu Làm Bài Trắc Nghiệm
            </button>
          </div>

        </div>

      </div>
    );
  }

  // ═══════════════════════════════════════════════════════════════
  // 2. ACTIVE QUIZ SCREEN (Interactive questions with timer)
  // ═══════════════════════════════════════════════════════════════
  if (quizMode === 'active') {
    const currentQ = activeQuestions[currentIdx];
    const isAnswered = selectedAnswers[currentQ?.id] !== undefined;
    const userAnswer = selectedAnswers[currentQ?.id];
    const isBookmarked = bookmarkedIds.includes(currentQ?.id);

    return (
      <div className="max-w-3xl mx-auto px-4 py-6 space-y-6">
        
        {/* Top Sticky Status Bar */}
        <div className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-2xl p-4 flex items-center justify-between shadow-xs">
          <div className="flex items-center space-x-3">
            <span className="font-extrabold text-sm text-slate-800 dark:text-slate-100">
              Câu {currentIdx + 1} / {activeQuestions.length}
            </span>
            <div className="w-24 sm:w-36 bg-slate-100 dark:bg-slate-800 h-2 rounded-full overflow-hidden">
              <div
                className="bg-rose-500 h-full transition-all duration-300"
                style={{ width: `${((currentIdx + 1) / activeQuestions.length) * 100}%` }}
              />
            </div>
          </div>

          <div className="flex items-center space-x-3">
            <div className="flex items-center gap-1.5 px-3 py-1.5 rounded-xl bg-amber-50 dark:bg-amber-950/60 border border-amber-200 dark:border-amber-800 text-amber-700 dark:text-amber-300 font-mono font-bold text-xs">
              <Clock className="w-3.5 h-3.5" />
              <span>{formatTime(timeLeftSeconds)}</span>
            </div>

            <button
              onClick={handleFinishQuiz}
              className="px-3.5 py-1.5 bg-rose-600 hover:bg-rose-700 text-white rounded-xl text-xs font-bold transition shadow-2xs cursor-pointer"
            >
              Nộp Bài
            </button>
          </div>
        </div>

        {/* Current Question Card */}
        <div className="bg-white dark:bg-slate-900 border-2 border-slate-200 dark:border-slate-800 rounded-3xl p-6 sm:p-8 space-y-6 shadow-sm">
          
          <div className="flex items-start justify-between gap-4">
            <h3 className="text-base sm:text-lg font-black text-slate-900 dark:text-white leading-relaxed">
              {currentQ.question}
            </h3>

            <button
              onClick={() => onToggleBookmark(currentQ.id)}
              className={`p-2 rounded-xl border transition cursor-pointer shrink-0 ${
                isBookmarked
                  ? 'bg-amber-50 dark:bg-amber-950 text-amber-600 border-amber-300'
                  : 'bg-slate-50 dark:bg-slate-800 text-slate-400 border-slate-200 dark:border-slate-700'
              }`}
              title="Đánh dấu câu hỏi để xem lại"
            >
              <Bookmark className={`w-4 h-4 ${isBookmarked ? 'fill-current' : ''}`} />
            </button>
          </div>

          {/* Options Grid (A, B, C, D) */}
          <div className="space-y-3">
            {currentQ.options.map((opt, optIdx) => {
              let optStyle =
                'bg-slate-50 dark:bg-slate-800/80 border-slate-200 dark:border-slate-700 text-slate-800 dark:text-slate-200 hover:border-indigo-400';

              if (isAnswered) {
                if (optIdx === currentQ.correctIndex) {
                  optStyle =
                    'bg-emerald-50 dark:bg-emerald-950/80 border-emerald-500 text-emerald-900 dark:text-emerald-200 font-bold ring-1 ring-emerald-500';
                } else if (userAnswer === optIdx) {
                  optStyle =
                    'bg-rose-50 dark:bg-rose-950/80 border-rose-500 text-rose-900 dark:text-rose-200 font-bold ring-1 ring-rose-500';
                } else {
                  optStyle = 'opacity-40 bg-slate-50 dark:bg-slate-800 border-slate-200 dark:border-slate-700';
                }
              }

              return (
                <button
                  key={optIdx}
                  onClick={() => handleSelectAnswer(currentQ.id, optIdx)}
                  disabled={isAnswered}
                  className={`w-full text-left p-4 rounded-2xl border transition-all flex items-center justify-between gap-3 text-xs sm:text-sm font-semibold cursor-pointer ${optStyle}`}
                >
                  <div className="flex items-center gap-3">
                    <span className="w-6 h-6 rounded-lg bg-white dark:bg-slate-700 flex items-center justify-center font-bold text-xs shadow-2xs">
                      {String.fromCharCode(65 + optIdx)}
                    </span>
                    <span>{opt}</span>
                  </div>

                  {isAnswered && optIdx === currentQ.correctIndex && (
                    <CheckCircle className="w-4 h-4 text-emerald-500 shrink-0" />
                  )}
                  {isAnswered && userAnswer === optIdx && optIdx !== currentQ.correctIndex && (
                    <XCircle className="w-4 h-4 text-rose-500 shrink-0" />
                  )}
                </button>
              );
            })}
          </div>

          {/* Explanation Box on Answered */}
          {isAnswered && (
            <div className="p-4 bg-indigo-50/70 dark:bg-indigo-950/40 border border-indigo-200 dark:border-indigo-800 rounded-2xl text-xs space-y-1 animate-in fade-in">
              <div className="font-extrabold text-indigo-900 dark:text-indigo-200 flex items-center gap-1.5">
                <Sparkles className="w-3.5 h-3.5 text-indigo-600 dark:text-indigo-400" />
                Giải Thích Chi Tiết:
              </div>
              <p className="text-slate-700 dark:text-slate-300 leading-relaxed">
                {currentQ.explanation}
              </p>
            </div>
          )}

        </div>

        {/* Navigation Buttons */}
        <div className="flex items-center justify-between pt-2">
          <button
            onClick={() => setCurrentIdx((prev) => Math.max(0, prev - 1))}
            disabled={currentIdx === 0}
            className="flex items-center gap-1 px-4 py-2.5 bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 text-slate-700 dark:text-slate-200 hover:bg-slate-50 dark:hover:bg-slate-800 disabled:opacity-40 rounded-xl text-xs font-bold transition cursor-pointer"
          >
            <ChevronLeft className="w-4 h-4" /> Câu Trước
          </button>

          {currentIdx === activeQuestions.length - 1 ? (
            <button
              onClick={handleFinishQuiz}
              className="flex items-center gap-1.5 px-6 py-2.5 bg-rose-600 hover:bg-rose-700 text-white rounded-xl text-xs font-bold transition shadow-sm cursor-pointer"
            >
              Hoàn Thành & Nộp Bài
            </button>
          ) : (
            <button
              onClick={() => setCurrentIdx((prev) => Math.min(activeQuestions.length - 1, prev + 1))}
              className="flex items-center gap-1 px-5 py-2.5 bg-indigo-600 hover:bg-indigo-700 text-white rounded-xl text-xs font-bold transition shadow-sm cursor-pointer"
            >
              Câu Tiếp <ChevronRight className="w-4 h-4" />
            </button>
          )}
        </div>

      </div>
    );
  }

  // ═══════════════════════════════════════════════════════════════
  // 3. SUMMARY SCREEN (Score, stats, detailed answers review)
  // ═══════════════════════════════════════════════════════════════
  let correctTotal = 0;
  activeQuestions.forEach((q) => {
    if (selectedAnswers[q.id] === q.correctIndex) {
      correctTotal++;
    }
  });

  const percentScore = Math.round((correctTotal / (activeQuestions.length || 1)) * 100);

  return (
    <div className="max-w-4xl mx-auto px-4 py-8 space-y-8">
      
      {/* Score Summary Box */}
      <div className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-3xl p-8 text-center space-y-6 shadow-sm">
        <div className="inline-flex items-center justify-center w-16 h-16 rounded-full bg-rose-50 dark:bg-rose-950/80 text-rose-600 dark:text-rose-400">
          <Award className="w-8 h-8" />
        </div>

        <div className="space-y-1">
          <h2 className="text-2xl sm:text-3xl font-black text-slate-800 dark:text-slate-100">
            Kết Quả Bài Luyện Trắc Nghiệm
          </h2>
          <p className="text-xs text-slate-500 dark:text-slate-400">
            Chủ đề: {currentTopicObj?.title}
          </p>
        </div>

        {/* 4 KPI Metrics */}
        <div className="grid grid-cols-2 sm:grid-cols-4 gap-4 max-w-xl mx-auto py-2">
          <div className="p-4 rounded-2xl bg-slate-50 dark:bg-slate-800/60 border border-slate-200 dark:border-slate-700">
            <div className="text-2xl font-black text-indigo-600 dark:text-indigo-400">
              {correctTotal}/{activeQuestions.length}
            </div>
            <div className="text-[11px] font-bold text-slate-500">Số Câu Đúng</div>
          </div>

          <div className="p-4 rounded-2xl bg-slate-50 dark:bg-slate-800/60 border border-slate-200 dark:border-slate-700">
            <div className="text-2xl font-black text-emerald-600 dark:text-emerald-400">
              {percentScore}%
            </div>
            <div className="text-[11px] font-bold text-slate-500">Tỷ Lệ Chính Xác</div>
          </div>

          <div className="p-4 rounded-2xl bg-slate-50 dark:bg-slate-800/60 border border-slate-200 dark:border-slate-700">
            <div className="text-2xl font-black text-amber-600 dark:text-amber-400">
              {formatTime(selectedDurationMinutes * 60 - timeLeftSeconds)}
            </div>
            <div className="text-[11px] font-bold text-slate-500">Thời Gian</div>
          </div>

          <div className="p-4 rounded-2xl bg-slate-50 dark:bg-slate-800/60 border border-slate-200 dark:border-slate-700">
            <div
              className={`text-2xl font-black ${
                percentScore >= 70 ? 'text-emerald-600 dark:text-emerald-400' : 'text-rose-600 dark:text-rose-400'
              }`}
            >
              {percentScore >= 70 ? 'XUẤT SẮC' : 'CẦN ÔN'}
            </div>
            <div className="text-[11px] font-bold text-slate-500">Đánh Giá</div>
          </div>
        </div>

        <div className="flex justify-center gap-3 pt-2">
          <button
            onClick={() => setQuizMode('selection')}
            className="px-6 py-3 bg-gradient-to-r from-rose-600 to-indigo-600 hover:from-rose-700 hover:to-indigo-700 text-white rounded-2xl text-xs font-bold transition shadow-sm cursor-pointer flex items-center gap-2"
          >
            <RotateCcw className="w-4 h-4" /> Làm Bài Thi Khác
          </button>

          <button
            onClick={() => setFilterWrongOnly(!filterWrongOnly)}
            className={`px-5 py-3 rounded-2xl text-xs font-bold border transition cursor-pointer ${
              filterWrongOnly
                ? 'bg-rose-50 dark:bg-rose-950/80 border-rose-300 text-rose-700 dark:text-rose-300'
                : 'bg-white dark:bg-slate-800 border-slate-200 dark:border-slate-700 text-slate-700 dark:text-slate-200 hover:bg-slate-50'
            }`}
          >
            {filterWrongOnly ? 'Xem Tất Cả Câu' : 'Chỉ Xem Câu Sai'}
          </button>
        </div>
      </div>

      {/* Detailed Question Review List */}
      <div className="space-y-4">
        <h3 className="text-base font-extrabold text-slate-900 dark:text-slate-100">
          Chi Tiết Toàn Bộ Câu Hỏi ({activeQuestions.length} câu)
        </h3>

        {activeQuestions.map((q, idx) => {
          const userAns = selectedAnswers[q.id];
          const isCorrect = userAns === q.correctIndex;

          if (filterWrongOnly && isCorrect) return null;

          return (
            <div
              key={q.id}
              className={`p-6 rounded-3xl border bg-white dark:bg-slate-900 space-y-4 shadow-2xs ${
                isCorrect
                  ? 'border-emerald-200 dark:border-emerald-900/60'
                  : 'border-rose-200 dark:border-rose-900/60'
              }`}
            >
              <div className="flex items-start justify-between gap-3">
                <h4 className="text-xs sm:text-sm font-bold text-slate-800 dark:text-slate-100 leading-relaxed">
                  Câu {idx + 1}: {q.question}
                </h4>
                <span
                  className={`px-3 py-0.5 rounded-full text-[10px] font-black shrink-0 ${
                    isCorrect
                      ? 'bg-emerald-100 dark:bg-emerald-950 text-emerald-800 dark:text-emerald-300'
                      : 'bg-rose-100 dark:bg-rose-950 text-rose-800 dark:text-rose-300'
                  }`}
                >
                  {isCorrect ? 'ĐÚNG' : 'SAI'}
                </span>
              </div>

              <div className="grid grid-cols-1 sm:grid-cols-2 gap-2 text-xs">
                {q.options.map((opt, optIdx) => {
                  let optStyle =
                    'bg-slate-50 dark:bg-slate-800/60 border-slate-200 dark:border-slate-700 text-slate-600 dark:text-slate-300';
                  if (optIdx === q.correctIndex) {
                    optStyle =
                      'bg-emerald-50 dark:bg-emerald-950/80 border-emerald-300 dark:border-emerald-800 text-emerald-900 dark:text-emerald-200 font-bold';
                  } else if (userAns === optIdx && !isCorrect) {
                    optStyle =
                      'bg-rose-50 dark:bg-rose-950/80 border-rose-300 dark:border-rose-800 text-rose-900 dark:text-rose-200 font-bold';
                  }

                  return (
                    <div
                      key={optIdx}
                      className={`p-3 rounded-xl border flex items-center gap-2 ${optStyle}`}
                    >
                      <span className="font-bold text-[11px]">
                        {String.fromCharCode(65 + optIdx)}.
                      </span>
                      <span>{opt}</span>
                    </div>
                  );
                })}
              </div>

              <div className="p-3.5 bg-slate-50 dark:bg-slate-800/80 rounded-2xl text-xs text-slate-600 dark:text-slate-300 leading-relaxed">
                <span className="font-extrabold text-slate-800 dark:text-slate-200">
                  Giải thích:
                </span>{' '}
                {q.explanation}
              </div>
            </div>
          );
        })}
      </div>

    </div>
  );
};
