// ═══════════════════════════════════════════════════════════════
// HỆ THỐNG PHÂN LOẠI TỪ VỰNG TIẾNG ANH (LULU & MIMI)
// ═══════════════════════════════════════════════════════════════

// Loại mục từ vựng
export type VocabType = 'word' | 'idiom' | 'collocation' | 'phrasal-verb';

// Dạng từ (Word Form / Part of Speech)
export type WordForm =
  | 'noun'
  | 'verb'
  | 'adjective'
  | 'adverb'
  | 'preposition'
  | 'conjunction'
  | 'pronoun'
  | 'phrase'
  | 'idiom';

// Mã định danh chủ đề (Topic ID)
export type TopicId =
  | 'all'
  | 'daily'
  | 'ielts'
  | 'toeic'
  | 'business'
  | 'academic'
  | 'travel'
  | 'technology'
  | 'custom';

// Dạng từ / Họ từ (Word Forms)
export interface WordFormItem {
  form: WordForm;
  word: string;
  meaningVi?: string;
  definitionEn?: string; // 🇬🇧 Định nghĩa tiếng Anh cho từng dạng từ
  ipa?: string;          // Phiên âm IPA
}
export type WordFamilyItem = WordFormItem; // Alias tương thích

// Dữ liệu thuật toán lặp lại ngắt quãng (SM-2 Spaced Repetition)
export interface SRSCardData {
  cardId: string;
  repetitions: number;          // Số lần đã ôn tập thành công liên tiếp (n)
  interval: number;             // Khoảng cách ngày đến lần ôn tới (I)
  easeFactor: number;           // Hệ số dễ nhớ (EF - mặc định 2.5)
  nextReviewDate: string;       // Thời điểm đến hạn ôn tập tiếp theo (ISO string)
  lastReviewedDate?: string;    // Lần ôn gần nhất (ISO string)
  memoryLevel: 1 | 2 | 3 | 4 | 5; // 1: Mới học, 2: Nhận biết, 3: Đang nhớ, 4: Thành thạo, 5: Trí nhớ dài hạn
}

// Thẻ Flashcard Từ Vựng
export interface Flashcard {
  id: string;
  topic: TopicId | string;
  vocabType: VocabType;
  wordForm?: WordForm;
  front: string;                    // Từ/Cụm từ tiếng Anh
  back: string;                     // Nghĩa tiếng Việt
  definitionEn?: string;            // 🇬🇧 Định nghĩa chuẩn bằng tiếng Anh
  pronunciation?: string;           // IPA (ví dụ: /əˈkɑːm.plɪʃ/)
  pronunciationUk?: string;         // IPA UK
  pronunciationUs?: string;         // IPA US
  audioUk?: string;                 // Link audio phát âm UK (.mp3)
  audioUs?: string;                 // Link audio phát âm US (.mp3)
  example?: string;                 // Câu ví dụ tiếng Anh
  exampleVi?: string;               // Dịch câu ví dụ tiếng Việt
  synonyms?: string[];              // Từ đồng nghĩa
  antonyms?: string[];              // Từ trái nghĩa
  collocations?: string[];          // Các cụm từ thường đi kèm
  wordForms?: WordFormItem[];       // Họ từ / Các dạng từ (Noun, Verb, Adj, Adv)
  wordFamily?: WordFormItem[];      // Alias cũ tương thích dữ liệu JSON
  notes?: string;                   // Mẹo ghi nhớ / Lưu ý ngữ cảnh
  isCustom?: boolean;               // Thẻ do người dùng tự tạo
  createdAt?: string;               // Ngày tạo thẻ (ISO string)
  difficulty?: 'Easy' | 'Medium' | 'Hard';
  srsData?: SRSCardData;            // Dữ liệu thuật toán lặp lại ngắt quãng
}

// Cấu Hình Tùy Chọn Nội Dung Hiển Thị Ở Mặt Sau Flashcard
export interface BackFaceDisplayConfig {
  showVietnameseMeaning: boolean; // 🇻🇳 Nghĩa tiếng Việt
  showDefinitionEn: boolean;      // 🇬🇧 Định nghĩa tiếng Anh
  showExample: boolean;           // 📝 Câu ví dụ
  showCollocations: boolean;      // 🔗 Cụm từ đi kèm (Collocations)
  showSynonymsAntonyms: boolean;  // ⚖️ Từ đồng nghĩa & Trái nghĩa
  showWordForms: boolean;         // 🌳 Họ từ / Biến thể (Word Forms)
  showWordAndIpa: boolean;        // 🎙️ Từ vựng & Phiên âm IPA
  showPartOfSpeech: boolean;      // 🏷️ Loại từ (Part of Speech)
}

export const DEFAULT_BACK_FACE_CONFIG: BackFaceDisplayConfig = {
  showVietnameseMeaning: true,
  showDefinitionEn: true,
  showExample: true,
  showCollocations: true,
  showSynonymsAntonyms: true,
  showWordForms: true,
  showWordAndIpa: true,
  showPartOfSpeech: true,
};

// Chủ Đề / Thư Mục Học Tập (Folder / Topic)
export interface Topic {
  id: TopicId | string;
  title: string;
  description?: string;
  iconName?: string;
  color?: string;                    // Tailwind gradient class
  badgeColor?: string;
  emoji?: string;                    // Emoji đại diện cho Thư mục
  isCustom?: boolean;                // Thư mục do người dùng tự tạo
  createdAt?: string;
  flashcardCount?: number;
  questionCount?: number;
}

// Câu Hỏi Trắc Nghiệm (Quiz Question)
export interface Question {
  id: number;
  question: string;
  options: string[];
  correctIndex: number;
  explanation: string;
  topic: TopicId | string;
  vocabType?: VocabType;
  difficulty?: 'Easy' | 'Medium' | 'Hard';
  isAutoGenerated?: boolean;
}

// Kết Quả Một Bài Thi Trắc Nghiệm
export interface QuizResult {
  id: string;
  date: string;
  topic: string;
  score: number;
  total: number;
  timeSpentSeconds: number;
  answers: { [questionId: number]: number };
}

// Tiến Độ & Dữ Liệu Người Dùng (Persist vào LocalStorage)
export interface UserProgress {
  masteredFlashcardIds: string[];
  needReviewFlashcardIds: string[];
  deletedCardIds?: string[];         // Danh sách ID các thẻ đã bị người dùng xóa
  quizHistory: QuizResult[];
  bookmarkedQuestions: number[];
  customFlashcards: Flashcard[];
  customTopics?: Topic[];            // Danh sách các Thư Mục do người dùng tự tạo / chỉnh sửa
  searchHistory: string[];
  srsRecords?: { [cardId: string]: SRSCardData }; // Bảng lưu trạng thái Spaced Repetition từng thẻ
}

// ═══════════════════════════════════════════════════════════════
// DICTIONARY LOOKUP & API TYPES (Cambridge & Free Dictionary)
// ═══════════════════════════════════════════════════════════════

export interface PhoneticInfo {
  text: string;
  audio?: string;
  region?: 'UK' | 'US' | 'General';
}

export interface DictDefinition {
  definition: string;
  example?: string;
  exampleVi?: string;
  synonyms?: string[];
  antonyms?: string[];
}

export interface DictMeaning {
  partOfSpeech: WordForm | string;
  definitions: DictDefinition[];
  synonyms?: string[];
  antonyms?: string[];
}

export type DictSource = 'free-dictionary' | 'cambridge' | 'ai-generated' | 'local';

export interface DictionaryResult {
  word: string;
  phonetics: PhoneticInfo[];
  meanings: DictMeaning[];
  synonyms: string[];
  antonyms: string[];
  examples: string[];
  collocations?: string[];
  wordForms?: WordFormItem[];
  wordFamily?: WordFormItem[];
  sourceUrls?: string[];
  sources: DictSource[];
  vietnameseMeaning?: string;
  englishDefinition?: string;
}

// Tin nhắn AI Chat
export interface ChatMessage {
  id: string;
  role: 'user' | 'assistant';
  content: string;
  suggestedFlashcard?: Partial<Flashcard>;
  timestamp: string;
}
